### ISSUE TITLE
Numbering scheme clashes with OWASP Top 10

### ISSUE THREAD

**Issue by bkimminich** [OWASP/Serverless-Top-10-Project#16]
Identical to the API Top 10 (https://github.com/OWASP/API-Security/issues/24) the current numbering scheme is `A1:2017`, `A2:2017` etc. which is exactly identical to the OWASP Top 10 scheme. This could cause immediate confusion as people might confuse entries from both lists. This is being made worse by the fact that both list entries are mostly the same anyway.

For comparison, the Docker Top 10 (https://github.com/OWASP/Docker-Security) avoid this by using `D1`, `D2` etc. as their numbering scheme. (They lack the year of document release though. See https://github.com/OWASP/Docker-Security/issues/13)

## Recommendation

Change numbering scheme into `S1:2019` or `SL1:2019` etc. to avoid clash with OWASP Top 10 and other Top 10 lists.

**Comment by MarcinHoppe** [comment]
@bkimminich Thanks for raising this! I think it makes a lot of sense. I will soon file a PR to address this.
